### ISSUE TITLE
Update to use `auth0/login` Laravel SDK

### ISSUE THREAD

**Issue by evansims** [auth0-developer-hub/api_laravel_php_hello-world_php-sdk#1]
👋  This example/documentation should be updated to implement [the `auth0/login` Laravel SDK](https://github.com/auth0/laravel-auth0), or to more clearly identify that this is an alternative integration path rather than the recommended approach.

**Comment by byron-okta** [comment]
Hi, @evansims; thank you for the feedback. We have released a [code sample](https://github.com/auth0-developer-hub/api_laravel_php_hello-world_php-sdk) that uses the Laravel SDK and included a paragraph suggesting using the code sample with the Laravel SDK in our [code sample page](https://developer.auth0.com/resources/code-samples/api/laravel/basic-authorization/php-php-sdk).
